name: deploy

on:
  push:
    branches:
      - develop   # trigger deployment from develop branch
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install
          npm install -g mermaid.cli

      - name: Fix permissions
        run: chmod a+x bin/*

      - name: Deploy website
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          bash bin/deploy --verbose --src develop --deploy gh-pages
